# Generated by Django 4.1.3 on 2022-11-11 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='gender_of_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='users/images/')),
                ('mobile_number', models.CharField(default='0000000000', max_length=10, validators=[users.models.validate_phone])),
                ('no_of_properties_sold', models.PositiveIntegerField(default=0)),
                ('no_of_properties_bought', models.PositiveIntegerField(default=0)),
                ('is_premium_agent', models.BooleanField(default=False)),
                ('is_premium_client', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0, null=True)),
                ('gender', models.ForeignKey(default=(), null=True, on_delete=users.models.gender_default, to='users.gender_of_user')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
