# Generated by Django 4.1.3 on 2022-11-14 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_property_details_map_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_remove_users_no_of_properties_bought_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.ForeignKey(default=(), null=True, on_delete=users.models.gender_default, to='users.gender_of_user'),
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
