# Generated by Django 4.1.3 on 2022-11-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='pincode',
        ),
        migrations.DeleteModel(
            name='pincode',
        ),
    ]
