# Generated by Django 4.1.3 on 2022-11-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_property_pincode_delete_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_details',
            name='map',
            field=models.URLField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3608.245529510468!2d82.98718481532006!3d25.262324683865955!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x398e3320e885927b%3A0x78ac04d1bac708f0!2sIIT%20(BHU)%20Varanasi!5e0!3m2!1sen!2sin!4v1668187631852!5m2!1sen!2sin', max_length=500),
        ),
        migrations.AddField(
            model_name='property_details',
            name='yt_video',
            field=models.URLField(default='https://www.youtube.com/watch?v=oHg5SJYRHA0'),
        ),
    ]
