# Generated by Django 4.1.3 on 2022-11-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_details_map_property_details_yt_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_details',
            name='map',
            field=models.CharField(default='<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3608.2455290309986!2d82.98937350000001!3d25.2623247!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x398e3320e885927b%3A0x78ac04d1bac708f0!2sIIT%20(BHU)%20Varanasi!5e0!3m2!1sen!2sin!4v1668192349845!5m2!1sen!2sin" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>', max_length=500),
        ),
        migrations.AlterField(
            model_name='property_details',
            name='yt_video',
            field=models.CharField(default='<iframe width="560" height="315" src="https://www.youtube.com/embed/oHg5SJYRHA0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>', max_length=200),
        ),
    ]
