# Generated by Django 4.1.3 on 2022-11-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_property_details_map_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_details',
            name='yt_video',
            field=models.CharField(default='<iframe width="560" height="315" src="https://www.youtube.com/embed/oHg5SJYRHA0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>', max_length=500),
        ),
    ]
