# Generated by Django 4.1.3 on 2022-11-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_property_details_map_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_details',
            name='yt_video',
            field=models.CharField(default='https://player.vimeo.com/video/73221098', max_length=500),
        ),
    ]
