# Generated by Django 4.1.3 on 2022-11-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_property_details_map_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_details',
            name='map',
            field=models.URLField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3608.2455290309986!2d82.98937350000001!3d25.2623247!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x398e3320e885927b%3A0x78ac04d1bac708f0!2sIIT%20(BHU)%20Varanasi!5e0!3m2!1sen!2sin!4v1668192349845!5m2!1sen!2sin', max_length=500),
        ),
        migrations.AlterField(
            model_name='property_details',
            name='yt_video',
            field=models.URLField(blank=True, default='https://player.vimeo.com/video/73221098', max_length=500),
        ),
    ]
